### ISSUE TITLE
LP 5.0.0 does not play well with PlaceholderAPI expansion

### ISSUE THREAD

**Issue by SlimeDog** [LuckPerms/LuckPermsPlaceholders#12]
Spigot 1.14.4 (Jenkins 2494)
LuckPerms 5.0.0
PlaceholderAPI 2.10.4

On server start-up:
```
[12:58:56] [Server thread/ERROR]: Could not pass event ServerLoadEvent to PlaceholderAPI v2.10.4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar-2019-11-22-1736:git-Spigot-56f8471-ccd47a5]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar-2019-11-22-1736:git-Spigot-56f8471-ccd47a5]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) [spigot-1.14.4.jar-2019-11-22-1736:git-Spigot-56f8471-ccd47a5]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) [spigot-1.14.4.jar-2019-11-22-1736:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:450) [spigot-1.14.4.jar-2019-11-22-1736:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266) [spigot-1.14.4.jar-2019-11-22-1736:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [spigot-1.14.4.jar-2019-11-22-1736:git-Spigot-56f8471-ccd47a5]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoClassDefFoundError: me/lucko/luckperms/api/LuckPermsApi
        at me.lucko.luckperms.placeholders.LuckPermsExpansion.canRegister(LuckPermsExpansion.java:49) ~[?:?]
        at me.clip.placeholderapi.expansion.ExpansionManager.registerExpansion(ExpansionManager.java:102) ~[?:?]
        at me.clip.placeholderapi.expansion.ExpansionManager.registerAllExpansions(ExpansionManager.java:154) ~[?:?]
        at me.clip.placeholderapi.ServerLoadEventListener.onServerLoad(ServerLoadEventListener.java:52) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar-2019-11-22-1736:git-Spigot-56f8471-ccd47a5]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.api.LuckPermsApi
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at me.lucko.luckperms.placeholders.LuckPermsExpansion.canRegister(LuckPermsExpansion.java:49) ~[?:?]
        at me.clip.placeholderapi.expansion.ExpansionManager.registerExpansion(ExpansionManager.java:102) ~[?:?]
        at me.clip.placeholderapi.expansion.ExpansionManager.registerAllExpansions(ExpansionManager.java:154) ~[?:?]
        at me.clip.placeholderapi.ServerLoadEventListener.onServerLoad(ServerLoadEventListener.java:52) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar-2019-11-22-1736:git-Spigot-56f8471-ccd47a5]
        ... 7 more
```

**Comment by StirFryBeans** [comment]
Just a note, using Spigot 1.15.1, PAPI 2.10.5-DEV-82, and Luckperm's PAPI expansion build #20 from [here](https://ci.lucko.me/job/LuckPermsPlaceholders/) with the legacy API extension in luck perms, I still get this same error, and LuckPerms placeholder's do not work correctly.

**Comment by lucko** [comment]
Build no 20 will work with the latest (v5) versions of LP.

Download from here: https://luckperms.net/
